In [1]:
import pandas as pd

In [7]:
df=pd.DataFrame({
    "Order Date":[
        "2024-01-10",
        "2024-01-15",
        "2024-02-05",
        "2024-02-12",
        "2024-03-01",
        "2024-03-15",
        "2024-04-10",
        "2024-04-20",
        "2024-05-05",
        "2024-01-15"
    ],
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Laptop",
        "Moniter",
        "Mouse",
        "Printer",
        "Smartwatch",
        "Mouse"
    ],
    "Category":[
        "Electronics",
        "Accessories",
        "Office",
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Office",
        "Electronics",
        "Accessories",
    ],
    "Region":[
        "North",
        "South",
        "East",
        "West",
        "North",
        "South",
        "East",
        "West",
        "North",
        "South"
    ],
    "Quantity":[
        2,
        5,
        3,
        4,
        1,
        2,
        6,
        2,
        3,
        5
    ],
    "Sales":[
        50000,
        2500,
        9000,
        30000,
        55000,
        16000,
        3000,
        6000,
        45000,
        2500
    ],
    "Profit":[
        10000,
        500,
        1500,
        6000,
        11000,
        3000,
        None,
        1000,
        9000,
        500
    ]
})

In [8]:
print("ORIGINAL DATASET")

ORIGINAL DATASET

In [9]:
display(df)

   Order Date Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5  2024-03-15      Moniter  Accessories  South         2  16000   3000.0
6  2024-04-10        Mouse  Accessories   East         6   3000      NaN
7  2024-04-20      Printer       Office   West         2   6000   1000.0
8  2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9  2024-01-15        Mouse  Accessories  South         5   2500    500.0

In [10]:
print("First 5 Records")

First 5 Records

In [11]:
display(df.head())

   Order Date Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  North         1  55000  11000.0

In [12]:
print("DATASET SHAPE")

DATASET SHAPE

In [13]:
print(df.shape)

(10, 7)

In [14]:
print("COLUMN NAMES")

COLUMN NAMES

In [15]:
print(df.columns)

Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='str')

In [16]:
print("DATA TYPES")

DATA TYPES

In [17]:
print(df.dtypes)

Order Date          str
Product Name        str
Category            str
Region              str
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [18]:
print("DESCRIPTIVE STATISTICS")

DESCRIPTIVE STATISTICS

In [19]:
display(df.describe())

        Quantity         Sales        Profit
count  10.000000     10.000000      9.000000
mean    3.300000  21900.000000   4722.222222
std     1.636392  21209.012759   4330.928820
min     1.000000   2500.000000    500.000000
25%     2.000000   3750.000000   1000.000000
50%     3.000000  12500.000000   3000.000000
75%     4.750000  41250.000000   9000.000000
max     6.000000  55000.000000  11000.000000

In [20]:
print("MISSING VALUES")

MISSING VALUES

In [21]:
print(df.isnull().sum())

Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          1
dtype: int64

In [22]:
print("ROWS CONTAINING MISSING VALUES")

ROWS CONTAINING MISSING VALUES

In [23]:
display(df[df.isnull().any(axis=1)])

   Order Date Product Name     Category Region  Quantity  Sales  Profit
6  2024-04-10        Mouse  Accessories   East         6   3000     NaN

In [24]:
print("TOTAL DUPLICATE RECORDS")

TOTAL DUPLICATE RECORDS

In [25]:
print(df.duplicated().sum())

1

In [26]:
print("DUPLICATE RECORDS")

DUPLICATE RECORDS

In [27]:
display(df[df.duplicated()])

   Order Date Product Name     Category Region  Quantity  Sales  Profit
9  2024-01-15        Mouse  Accessories  South         5   2500   500.0

In [28]:
import pandas as pd

In [29]:
new_sales=pd.DataFrame({
    "Order Date":[
        "2024-06-01",
        "2024-06-05",
        "2024-06-10",
    ],
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
    ],
    "Category":[
        "Electronics",
        "Accessories",
        "Office"
    ],
    "Region":[
        "North",
        "South",
        "East",
    ],
    "Quantity":[
        2,
        4,
        3
    ],
    "Sales":[
        60000,
        2000,
        9000
    ],
    "Profit":[
        12000,
        400,
        1800
    ]
})

In [30]:
print("NEW SALES DATA")

NEW SALES DATA

In [31]:
display(new_sales)

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-06-01       Laptop  Electronics  North         2  60000   12000
1  2024-06-05        Mouse  Accessories  South         4   2000     400
2  2024-06-10      Printer       Office   East         3   9000    1800

In [32]:
combined_df=pd.concat(
    [df,new_sales],
    ignore_index=True
)

In [33]:
print("CONCATENATED DATA")

CONCATENATED DATA

In [34]:
display(combined_df)

    Order Date Product Name     Category Region  Quantity  Sales   Profit
0   2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1   2024-01-15        Mouse  Accessories  South         5   2500    500.0
2   2024-02-05      Printer       Office   East         3   9000   1500.0
3   2024-02-12       Tablet  Electronics   West         4  30000   6000.0
4   2024-03-01       Laptop  Electronics  North         1  55000  11000.0
5   2024-03-15      Moniter  Accessories  South         2  16000   3000.0
6   2024-04-10        Mouse  Accessories   East         6   3000      NaN
7   2024-04-20      Printer       Office   West         2   6000   1000.0
8   2024-05-05   Smartwatch  Electronics  North         3  45000   9000.0
9   2024-01-15        Mouse  Accessories  South         5   2500    500.0
10  2024-06-01       Laptop  Electronics  North         2  60000  12000.0
11  2024-06-05        Mouse  Accessories  South         4   2000    400.0
12  2024-06-10      Printer       Office   East         3   9000   1800.0

In [35]:
import pandas as pd

In [36]:
product_info=pd.DataFrame({
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Moniter",
    ],
    "Supplier":[
        "DELL",
        "Logitech",
        "HP",
        "Samsung",
        "LG"
    ],
    "Discount":[
        10,
        5,
        15,
        8,
        12
    ]
})

In [37]:
print("PRODUCT INFORMATION")

PRODUCT INFORMATION

In [38]:
display(product_info)

  Product Name  Supplier  Discount
0       Laptop      DELL        10
1        Mouse  Logitech         5
2      Printer        HP        15
3       Tablet   Samsung         8
4      Moniter        LG        12

In [39]:
merged_df=pd.merge(
    df,
    product_info,
    on="Product Name",
    how="left"
)

In [40]:
print("MERGED DATA")

MERGED DATA

In [41]:
display(merged_df)

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,Supplier,Discount
0,2024-01-10,Laptop,Electronics,North,2,50000,10000.0,DELL,10.0
1,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0
2,2024-02-05,Printer,Office,East,3,9000,1500.0,HP,15.0
3,2024-02-12,Tablet,Electronics,West,4,30000,6000.0,Samsung,8.0
4,2024-03-01,Laptop,Electronics,North,1,55000,11000.0,DELL,10.0
5,2024-03-15,Moniter,Accessories,South,2,16000,3000.0,LG,12.0
6,2024-04-10,Mouse,Accessories,East,6,3000,NaN,Logitech,5.0
7,2024-04-20,Printer,Office,West,2,6000,1000.0,HP,15.0
8,2024-05-05,Smartwatch,Electronics,North,3,45000,9000.0,NaN,NaN
9,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0

In [42]:
region_info=pd.DataFrame(
    {
        "Region_Manager":[
            "Manager A",
            "Manager B",
            "Manager C",
            "Maneger D"
        ]
    },
    index=[
        "North",
        "South",
        "East",
        "West",
    ]
)

In [43]:
print("REGION INFORMATION")

REGION INFORMATION

In [44]:
display(region_info)

      Region_Manager
North      Manager A
South      Manager B
East       Manager C
West       Maneger D

In [45]:
df_region=df.set_index("Region")

In [47]:
joined_df=df_region.join(region_info)

In [48]:
print("JOINED DATA")

JOINED DATA

In [49]:
display(joined_df)

,Order Date,Product Name,Category,Quantity,Sales,Profit,Region_Manager
Region,,,,,,,
North,2024-01-10,Laptop,Electronics,2,50000,10000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B
East,2024-02-05,Printer,Office,3,9000,1500.0,Manager C
West,2024-02-12,Tablet,Electronics,4,30000,6000.0,Maneger D
North,2024-03-01,Laptop,Electronics,1,55000,11000.0,Manager A
South,2024-03-15,Moniter,Accessories,2,16000,3000.0,Manager B
East,2024-04-10,Mouse,Accessories,6,3000,NaN,Manager C
West,2024-04-20,Printer,Office,2,6000,1000.0,Maneger D
North,2024-05-05,Smartwatch,Electronics,3,45000,9000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B

In [50]:
region_sales=df.groupby(
    "Region"
)["Sales"].sum()

In [51]:
print("TOTAL SALES BY REGION")

TOTAL SALES BY REGION

In [52]:
display(region_sales)

Region
East      12000
North    150000
South     21000
West      36000
Name: Sales, dtype: int64

In [53]:
pivot_table=pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)

In [54]:
print("PIVOT TABLE")

PIVOT TABLE

In [55]:
display(pivot_table)

Region       East   North  South   West
Category
Accessories  3000       0  21000      0
Electronics     0  150000      0  30000
Office       9000       0      0   6000